### ISSUE TITLE
v1: About native eth_address and eth-tx-hash

### ISSUE THREAD

**Issue by Flouse** [nervina-labs/godwoken_explorer#276]
## Contract address showed on Explorer is unexpected.
deployed contract address: 0x741CA3C65C1Ff4cFCf46256D826cC23D1c105299
V1_gwScan shows it like: 0x79216784bca30993e02dbfbd8468f0ee43af392c ---> it's an id from 
https://api.v1.aggron.gwscan.com/api/search?keyword=0x741ca3c65c1ff4cfcf46256d826cc23d1c105299

Ref: [Address used in Polyjuice](https://github.com/nervosnetwork/godwoken-polyjuice/blob/compatibility-breaking-changes/README.md#address-used-in-polyjuice)

## txhash showed on Explorer is unexpected too
returned from interaction of Web3 RPC: 0x20940e01d1a10a9277bd6196d089d8fe1b29592b892e6d3213b781b2c2091ead
V1_gwScan shows: 0xe5e469e1f72981e26c73ade0656d3a5441e2a1430a9212e36b970cb72a058d41

Related Godwoken Web3 PR:
- https://github.com/nervosnetwork/godwoken-web3/pull/172

**Comment by zmcNotafraid** [comment]
@Flouse  It's Fixed
