### ISSUE TITLE
v1: The list of transaction is not in order

### ISSUE THREAD

**Issue by gpBlockchain** [nervina-labs/godwoken_explorer#283]
Transactions in the same block are not in order
like:https://v1.aggron.gwscan.com/account/0x966b30e576a4d6731996748b48dd67c94ef29067
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/32102187/158929010-fcbe993b-ac26-40b1-af04-8da6d948f5af.png">

**Comment by zmcNotafraid** [comment]
![image](https://user-images.githubusercontent.com/12708910/159219971-fbd05d17-d369-4984-88a7-c0cd8cac1e8a.png)
Before we not order by nonce.Now fixed.
