### ISSUE TITLE
v1: weird Contract address 0x1e7754142f594e986671a5750100000004000000

### ISSUE THREAD

**Issue by Flouse** [nervina-labs/godwoken_explorer#288]
![image](https://user-images.githubusercontent.com/1297478/158986625-2e806b87-05ee-4167-bf64-edeb3abd4b99.png)
A developer created a contract in ethers.js, it seems to show correct address right after creation.
But it is not visible from the explorer.

see:
https://v1.aggron.gwscan.com/tx/0x1d7b27f7d28125807bf24a3bdd8f5ff3c485f35e5d8736ab8945eb87d3125558

## The Interacted Contract is weird
[0x1e7754142f594e986671a5750100000004000000](https://v1.aggron.gwscan.com/account/0x1e7754142f594e986671a5750100000004000000)

## Related issue
- https://github.com/nervina-labs/godwoken_explorer/issues/276

**Comment by zmcNotafraid** [comment]
Now we add a job for create these account.

**Comment by zmcNotafraid** [comment]
0x841ce48f9446c8e281d3f1444cb859b4a6d073 is account  11262.
0x1e7754142f594e986671a5750100000004000000 is account id 6, as polyjuice creator id. Before I use script args last 20 bytes as eth_address.But it's not suitable for polyjuice creator id.

**Comment by zmcNotafraid** [comment]
![image](https://user-images.githubusercontent.com/12708910/159840225-59c5a160-3b65-4180-a7bc-90c1e6cb49c5.png)
Fixed
