### ISSUE TITLE
invalid json response body at ****

### ISSUE THREAD

**Issue by yixyxiu** [nervina-labs/godwoken_explorer#292]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/87553548/159103404-2aedcb8d-625c-4389-a7ad-199342133888.png">

Steps:
1. Visit https://gwscan.com/, Click TopNav -> Contracts
2. Select 「YokaiRouter」which the address is [0x1ac741946998fcdba3ba8ccff4797407eb30274e](https://gwscan.com/account/0x1ac741946998fcdba3ba8ccff4797407eb30274e).
3. Selecting 「ERC20 Transfers」triggers this ERROR:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/87553548/159103901-80490881-ca53-4eac-ba34-8582dd958ba8.png">

**Comment by zmcNotafraid** [comment]
It's fixed @yixyxiu
